# Generated by Django 4.0.4 on 2022-04-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200, null=True, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('random1', models.CharField(max_length=200)),
                ('forget_password_token', models.CharField(max_length=200)),
                ('signup_date', models.DateField(max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('register_token', models.CharField(max_length=200)),
            ],
        ),
    ]
