# Generated by Django 4.0.4 on 2022-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogonote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foldername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200)),
                ('foldername', models.CharField(max_length=255)),
                ('random1', models.CharField(max_length=200)),
                ('random2', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='notenames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=555)),
                ('random1', models.CharField(max_length=200)),
                ('random2', models.CharField(max_length=200)),
                ('random3', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
