# Generated by Django 2.1.15 on 2023-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogonote', '0002_foldername_notenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldername',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notenames',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
